### ISSUE TITLE
(已解决)在我本机上显示的昵称正常，但是线上就乱码了，请问怎么解决？

### ISSUE THREAD

**Issue by caotao0918** [quaintclever/easyposter#2]
您好，在我本机上显示的昵称正常，但是线上就乱码了，请问怎么解决？

**Comment by a417707897** [comment]
我也遇到同样的问题

**Comment by caotao0918** [comment]
已解决   重新实现一下作者的PosterDefaultImpl类，加个字体即可！

**Comment by a417707897** [comment]
> 已解决 重新实现一下作者的PosterDefaultImpl类，加个字体即可！

你的意思是继承PosterDefaultImpl类，重写drawTextImpl方法，然后toBuilder加个.font(new Font("Serif", Font.PLAIN, 10))就行了是吧
